### ISSUE TITLE
资源分享缺失

### ISSUE THREAD

**Issue by realism0331** [smallzhong/drip-education-homework#1]
练习所需程序(ipmsg.exe)在你分享的资源中没有找到

**Comment by smallzhong** [comment]
在那个压缩包里面有一个exe程序叫 `fg.exe` ，那个就是用来练习的飞鸽传书程序。和视频里面用的是一样的。

**Comment by realism0331** [comment]
好的谢谢，今天B站滴水官方账号把初级班视频资源给删了，emmmm……

**Comment by smallzhong** [comment]
有点离谱
都放了那么久了为啥现在删了
你去看雪和52pojie找找有没有百度网盘的资源吧。。

**Comment by realism0331** [comment]
好的，谢谢
