### ISSUE TITLE
大佬你好,滴水三期作业源码,PE头这部分还有吗?

### ISSUE THREAD

**Issue by jiuzhouhan996** [smallzhong/drip-education-homework#2]
从2015-03-11[PE头解析],到2015-03-31[导入表注入],全套源码,都齐了吗?

**Comment by smallzhong** [comment]
抱歉才看到。。
这些作业的代码都是我自己写的，每一天都是在前一天的基础上加的代码，PE部分的练习基本上都能在代码里面找到，导入表注入是唯一没写成功的，虽然注入到了导入表里面但是程序跑不起来，其他的都成功了的。

**Comment by smallzhong** [comment]
3-11的作业没有单独传，但是实现的逻辑应该可以在后面的代码里面找到的。

**Comment by Aiden-Johnson** [comment]
6-4的内存注入有吗
